- title: About KWM
  icon: /assets/img/headend/headend1.svg
  description: KHM is Korean school you can learn Korean
  button_label: Learn More
  url: /pages/explore-topics/
  
- title: Class
  icon: /assets/img/headend/headend2.svg
  description:  There are many classes
  button_label: Learn More
  url: /pages/faq/
  
- title: Registration
  icon: /assets/img/headend/headend3.svg
  description:  You can enroll any class from you needs
  button_label: Registrater
  url: /docs/left-sidebar-example
  